[workspace]
resolver = "2"
members = [
	"nodes/*",
	"utils/*",
	"tests/*",
	"contracts/*",
	"forked/*",
]
exclude = [
	"forked/substrate-contracts-node",
	"forked/substrate-node-template",
]

[profile.release]
panic = "abort"
