[package]
name = "kyber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.6.4"
sha3 = "0.10.8"

[dev-dependencies]
rand_core = { version = "0.6.4", features = ["getrandom"] }
